### ISSUE TITLE
asciidoc-multiple-inputs-example image missing in the pdf output.

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor-maven-examples#11] opened 2015-01-12 14:42 UTC
When I try to run the example `asciidoc-multiple-inputs-example` with maven on windows, there is no images in the output pdf document `example-manual.pdf`.

There is a `asciidoctor: WARNING:` line in the console log. asciidoctor seems to look for the picture at the `imagesdir` + `absolute path` + `imagesdir` location 

In the PDF document, in the **Attributes** section the value of _imagesdir_ is set to: "images"

Here the maven log:

    C:\{{path_to_git_repo}}\asciidoc-multiple-inputs-example>mvn install
    [INFO] Scanning for projects...
    [INFO]
    [INFO] ------------------------------------------------------------------------
    [INFO] Building AsciiDoc Multiple Input Documents Maven Example 1.0.0-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO]
    [INFO] --- asciidoctor-maven-plugin:1.5.2:process-asciidoc (asciidoc-usermanual-to-pdf) @ asciidoc-multiple-inputs-example ---
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    asciidoctor: WARNING: could not embed image; images/C:/{{path_to_git_repo}}/asciidoc-multiple-inputs-example/src/docs/asciidoc/user-manual/images/sunset.jpg not found
    [INFO] Rendered C:\{{path_to_git_repo}}\asciidoc-multiple-inputs-example\src\docs\asciidoc\user-manual\example-manual.adoc
    [INFO]
    [INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ asciidoc-multiple-inputs-example ---
    [debug] execute contextualize
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] skip non existing resourceDirectory C:\{{path_to_git_repo}}\asciidoc-multiple-inputs-example\src\main\resources
    [INFO]
    [INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ asciidoc-multiple-inputs-example ---
    [INFO] Nothing to compile - all classes are up to date
    [INFO]
    [INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ asciidoc-multiple-inputs-example ---
    [debug] execute contextualize
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] skip non existing resourceDirectory C:\{{path_to_git_repo}}\asciidoc-multiple-inputs-example\src\test\resources
    [INFO]
    [INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ asciidoc-multiple-inputs-example ---
    [INFO] No sources to compile
    [INFO]
    [INFO] --- maven-surefire-plugin:2.10:test (default-test) @ asciidoc-multiple-inputs-example ---
    [INFO] No tests to run.
    [INFO] Surefire report directory: C:\{{path_to_git_repo}}\asciidoc-multiple-inputs-example\target\surefire-reports

**Comment by abelsromero** [comment] 2015-01-12 21:04
Yes, this is a known (at least to me :cold_sweat: ) issue with the pdf backend. I am sorry to say that asciidoctor-pdf is currently still in alpha and some bugs are expected.

**Comment by mojavelinux** [comment] 2015-01-19 07:14
Is this reported in Asciidoctor PDF? If so, could you link to the issue so that we can navigate between them? Thanks!

**Comment by ecki** [comment] 2015-05-03 19:40
I have the same problem in all PDFs (including the docbook pipeline).

**Comment by mojavelinux** [comment] 2015-05-03 20:59
Image paths are not being calculated using the correct API in Asciidoctor PDF. Once we get this fixed, it will work correctly from Maven. See https://github.com/asciidoctor/asciidoctor-pdf/issues/87

**Comment by mojavelinux** [comment] 2015-05-03 21:01
I'm surprised this doesn't work in the docbook pipeline. Something else must be happening there.

**Comment by mojavelinux** [comment] 2015-05-03 21:03
Could you look at the following file in the docbook-pipeline-jdocbook-example project and tell me what the `fileref` attribute is on the `imagedata` element?

target/docbook/source/en-US/example-manual.xml

**Comment by mojavelinux** [comment] 2015-05-03 21:14
I have a feeling the way we are setting the imagesdir attribute in the Maven configuration is producing a path that Asciidoctor cannot correctly sanitize. We may need to figure out what we need to do to make the value cross platform.

**Comment by mojavelinux** [comment] 2015-05-03 22:15
I see the problem. The path to the image looks like:

C:\Users\IEUser\Downloads\asciidoctor-maven-examples\docbook-pipeline-jdocbook- example\target/docbook/source/en-US/images

Note the mix of slashes. The Maven property has backslashes, whereas the custom part in the configuration uses forward slashes. This confuses the DocBook toolchain, I'm sure. I'll think about how to proceed.

**Comment by mojavelinux** [comment] 2015-05-03 22:20
Correction. The fileref is being normalized. It looks like this:

C:/Users/IEUser/Downloads/asciidoctor-maven-examples/docbook-pipeline-jdocbook-example/target/docbook/source/en-US/images/sunset.jpg

I wonder of DocBook is confused by the forward slashes in the path. It shouldn't be. Still investigating.

**Comment by mojavelinux** [comment] 2015-05-03 23:19
I just pushed a fix that should get the DocBook examples working correctly on Windows.

One of the reasons I really hate the DocBook toolchain is because there are too many levels of indirection. This is especially true of the jDocBook toolchain. After doing some research on this issue, I can definitely see that docbkx is more viable, though it still has it's own path calculation issues.

We may still have issues with Asciidoctor PDF on Windows that I need to explore...but that should at least get the DocBook PDF story back in shape. Note that the values for the images paths are *extremely* sensitive, so if you touch them, things could break. The problem is that the DocBook toolchain doesn't seem to be very good at handling Windows paths...which is why we were getting double paths. This is really out of our control. We have to work with what we're given :/

**Comment by mojavelinux** [comment] 2015-05-03 23:24
Here's why Asciidoctor PDF doesn't work on Windows

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L576

You can see my note in the source code. We know it's broken because we aren't using the Windows-safe path calculation. A simple switch to using the proper API solves this issue. I'm confident this will cease to be a problem once that's fixed.

**Comment by ecki** [comment] 2015-05-04 08:48
Thanks, I can confirm the image shows up on the two docbook pipelines with f65a73c now. (Win7 x64 german, Maven 3.2.5, Java 8)

**Comment by mojavelinux** [comment] 2015-05-04 19:00
\o/

Thanks for testing!

**Comment by abelsromero** [comment] 2015-06-15 18:08
The images are showing now with asciidoctor `1.5.0-alpha.7`.
I guess we can close this issue. Any objection?

**Comment by tduchateau** [comment] 2015-06-15 19:07
I don't know if it's related but with the `1.5.0-alpha.7`, now I get this error:

````
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc (output-pdf) on project dandelion-docs: Execution output-pdf of goal org.asciidoctor:as
ciidoctor-maven-plugin:1.5.2.1:process-asciidoc failed: (UnknownFont) Icon font not found for set: fa -> [Help 1]
````

Both outputs (HTML and PDF) share the same configuration:

````
<configuration>
   <sourceHighlighter>coderay</sourceHighlighter>
   <sourceDirectory>src/asciidoc</sourceDirectory>
   <relativeBaseDir>true</relativeBaseDir>
   <gemPath>${project.build.directory}/gems-provided</gemPath>
   <attributes>
      <toc>left</toc>
      <icons>font</icons>
      <sectanchors>true</sectanchors>
      <idprefix />
      <idseparator>-</idseparator>
      <docinfo1>true</docinfo1>
      <project-version>${project.version}</project-version>
   </attributes>
</configuration>
````
I didn't change anything except the version of asciidoctor-pdf.

I'm using:

* org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1
* org.asciidoctor:asciidoctorj:1.5.2
* org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.7

With the previous version of asciidoctorj-pdf (1.5.0-alpha.6), I was hitting the same issue as the original one reported by @jmini.

**Comment by abelsromero** [comment] 2015-06-15 20:15
I just run the PDF examples with that configuration and I had no problem. 
Seeing the identifier `output-pdf` I guess this error is not related to the examples. If it's possible can you provide the text you're trying to parse, seems to me must be something in the document.

**Comment by mojavelinux** [comment] 2015-06-15 22:17
This is a known issue. You won't be able to use font-based icons with Asciidoctor PDF until the next alpha release (this week). When we make the jar, the FontAwesome font file got left out.

**Comment by jmini** [comment] 2015-12-22 12:17
With #38 the version will be set to:

 * asciidoctor.maven.plugin.version: 1.5.3
 * asciidoctorj.pdf.version: 1.5.0-alpha.10.1
 * asciidoctorj.version: 1.5.3.2
 * jruby.version: 9.0.4.0

And the mentioned example `asciidoc-multiple-inputs-example` works now great. I agree, we can close this bug.

**Comment by mojavelinux** [comment] 2015-12-22 21:30
:+1:

**Closed** 2015-12-22 21:31 UTC
Labels: tracking
