### ISSUE TITLE
dependency in examples needs to change from jruby-complete to jruby

### ISSUE THREAD

**Issue by Bananeweizen** [asciidoctor/asciidoctor-maven-examples#156] opened 2022-09-12 07:58 UTC
https://github.com/asciidoctor/asciidoctor-maven-plugin/commit/53d2cffb changed the dependency from `jruby-complete` to `jruby`. The examples however [still contain the old dependency](https://github.com/asciidoctor/asciidoctor-maven-examples/blob/187c376da6606e744781b04d7187c4aebc56dc7a/asciidoctor-pdf-example/pom.xml#L37), leading to problems at runtime, as reported in https://github.com/jruby/jruby/issues/7261.

**Comment by abelsromero** [comment] 2022-09-19 07:27
Back in the day there were some examples that required jruby-complete, because some extension/backend used an additional API.
I am for simplifying dependencies but I am wondering what is actually the issue since the tests pass. Could you provide a reproducer?

**Comment by pzygielo** [comment] 2022-09-19 07:47
> Could you provide a reproducer?

It's already there - update jruby from 9.3.4:
- https://github.com/asciidoctor/asciidoctor-maven-examples/pull/157

**Comment by abelsromero** [comment] 2022-09-20 17:14
I see, `-complete` did not remove the default `-core` 9.2.20.1.

**Comment by abelsromero** [comment] 2022-09-20 18:07
It's fixed in the repo, thanks @Bananeweizen and @pzygielo for reporting :tada:

**Closed** 2022-09-20 18:06 UTC
Labels: enhancement
